import re
import os

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    # Mapping of common Japanese comments to English
    # Using regex to find them even with varying spaces
    replacements = [
        (r'# --- プレイヤー クラス定義 ---', '# --- Player Class Definition ---'),
        (r'# 重力スキルのチェック', '# Gravity skill check'),
        (r'# ジャンプ入力判定 \(物理キー or スマホ上ボタン\)', '# Jump input detection (keys or smartphone button)'),
        (r'# スマホモード用の離散ジャンプ判定', '# Discrete jump detection for smartphone'),
        (r'# ジャンプ挙動', '# Jump behavior'),
        (r'# スキルアップデート', '# Skill updates'),
        (r'# ダッシュスキルのチェック', '# Dash skill check'),
        (r'# 一方通行足場判定 \(下からはすり抜けられる\)', '# One-way platform detection (passable from below)'),
        (r'# スマホモードの攻撃判定', '# Smartphone attack detection'),
        (r'# 当たり判定', '# Collision detection'),
        (r'当たり判定', 'Collision detection'),
        (r'当たった', 'Hit'),
        (r'# 状態異常の更新', '# Status effect updates'),
        (r'# 凍結中は物理と行動をスキップ', '# Skip physics and behavior while frozen'),
        (r'# 画面外への脱走を防止', '# Prevent screen escape'),
        (r'# 1秒ごとにダメージ', '# Damage every second'),
        (r'# READY中は動かない、ダメージも与えない', '# No move/damage during READY'),
        (r'# 画面外への脱走を防止 \(共通処理\)', '# Prevent screen escape (common)'),
        (r'# 落下中のみ速度0にして接地させる', '# Grounding when falling'),
        (r'# 一方通行足場判定 \(地上敵のみ\)', '# One-way platform detection (ground enemies only)'),
        (r'# 属性シナジー', '# Elemental synergy'),
        (r'# 凍結中はノックバックしない', '# No knockback while frozen'),
        (r'# 召喚エフェクト', '# Summoning effect'),
        (r'# 凍結中は青白く', '# Pale blue while frozen'),
        (r'# 炎エフェクト', '# Flame effect'),
        (r'# 模様', '# Patterns'),
        (r'# HPバー', '# HP Bar'),
        (r'# 衝撃波エフェクト', '# Shockwave effect'),
        (r'# 前のWaveの弾を消去', '# Clear previous wave bullets'),
        (r'# 転生者モードのみボスが出現するように制限', '# Boss spawn restricted to Reincarnator mode'),
        (r'# Wave 1 は 2体。2 Wave ごとに 1体ずつ増え、最大8体', '# Wave 1: 2 enemies. Increases by 1 every 2 waves, max 8'),
        (r'# 転生者モード以外は強化速度半減', '# Non-Reincarnator modes scale half as fast'),
        (r'# 敵の強化計算（Wave20以降は2waveおき、Wave40以降は1waveおき）', '# Enemy scaling: every 2 waves after W20, every wave after W40'),
        (r'# Wave進行に応じて新種を追加', '# Add new species as waves progress'),
        (r'# --- スマホモード時の仮想キー状態更新 ---', '# Update virtual key states for smartphone ---'),
        (r'# --- スマートフォン タッチ入力処理 ---', '# --- Smartphone touch processing ---'),
        (r'# スキルアイコンのタッチ判定 \(FINGERDOWN時のみ\)', '# Skill icon touch detection (FINGERDOWN only)'),
        (r'# アイコン領域\(40x40\)より少し広く判定\(60x60\)', '# Detection area (60x60) wider than icon (40x40)'),
        (r'「Character Selectへ進む」エリア', '"Character Select" area'),
        (r'「スマホモード切り替え」ボタン', '"Smartphone Mode" toggle button'),
        (r'# プレイヤー位置などをリセットし、戦闘開始', '# Reset player position and start battle'),
        (r'スマホモード判定領域 \(画面下部中央付近をタッチでもトグル可能にする\)', 'Smartphone mode toggle area'),
        (r'# REPLACE 状態に遷移した（waveは入れ替え後に開始）', '# Transitioned to REPLACE state (wave starts after)'),
        (r'# 報酬をスキップ \(スマホなら画面タップでもスキップ可能にする\)', '# Skip reward (can also tap on phone)'),
        (r'# 報酬適用', '# Apply reward'),
        (r'# アップグレード枠増加', '# Increase upgrade slots'),
        (r'# スキル進化', '# Skill evolution'),
        (r'所持スキルのうちランダム1つを強化', 'Enforce one random owned skill'),
        (r'# 英雄の加護', '# Hero\'s Blessing'),
        (r'# スキルを入れ替え', '# Swap skill'),
        (r'# 戦闘モード開始', '# Start combat mode'),
        (r'# 手動スポーン', '# Manual spawn'),
        (r'# ロジックの更新', '# Update logic'),
        (r'# 衝突分離', '# Collision separation'),
        (r'敵弾の更新', 'Update enemy bullets'),
        (r'# 全滅したら次のウェーブへ \(インターバルを挟む\)', '# Next wave when cleared (with interval)'),
        (r'# 2秒間待機', '# Wait 2 seconds'),
        (r'# ボス撃破後の特別報酬へ', '# Special reward after boss defeat'),
        (r'# 描画', '# Draw'),
        (r'# 足場の描画', '# Draw platform'),
        (r'# 地面固定', '# Fixed to ground'),
        (r'# 左右のパトロール挙動 \(画面端で反転\)', '# patrol behavior (flip at edges)'),
        (r'# プレイヤーとの距離を確認', '# Check distance to player'),
        (r'# 接近時に突進 \(クールタイム時のみ\)', '# Dash on approach (only when off cooldown)'),
        (r'# 突進方向に顔を向ける', '# Face the dash direction'),
        (r'# 通常時は一定速度で移動 \(突進中=vxが大きい時はそちらの物理挙動に任せる\)', '# Normal movement at constant speed'),
        (r'# 接近時のみ低確率ダッシュ', '# Low-chance dash when close'),
        (r'# それ以外は少し離れた空から積極的に射撃', '# Otherwise, actively shoot from the air'),
        (r'# 重力適用', '# Apply gravity'),
        (r'# 落下中のみ', '# Only while falling'),
        (r'# 着地時に横移動を止める', '# Stop horizontal movement on landing'),
        (r'# 地面にいて攻撃可能ならプレイヤーに向かってジャンプ', '# Jump toward player if on ground and ready'),
        (r'# 距離に応じて横軸速度を調整（少し手前に飛ぶように）', '# Adjust horizontal speed (aim slightly short)'),
        (r'# 通常時のパトロール（ジャンプしていない時のみ）', '# Normal patrol (only when not jumping)'),
        (r'# 接触ダメージ', '# Contact damage'),
        (r'# 回復行動', '# Heal action'),
        (r'# 十字マークを描画', '# Render cross mark'),
        (r'# 回復エフェクト', '# Healing effect'),
        (r'# プレイヤーに向かって高速突進', '# Dash toward player at high speed'),
        (r'# プレイヤーへのダメージ', '# Damage to player'),
        (r'# 周囲の敵へのダメージ', '# Damage to nearby enemies'),
        (r'# 大量の破片', '# Massive amount of debris'),
        (r'# 爆発エフェクト', '# Explosion effect'),
        (r'# 点滅する警告マーク', '# Blinking warning mark'),
        (r'# プレイヤーから距離を取る', '# Keep distance from player'),
        (r'# 狙撃: 予告 → 射撃の2段階', '# Snipe: Warning -> Shoot stages'),
        (r'予告線（レーザーサイト）', 'Warning line (laser sight)'),
        (r'# 照準マーク', '# Aim mark'),
        (r'# 着地時に衝撃波判定', '# Shockwave detection on landing'),
        (r'# 衝撃波ダメージ（プレイヤーが地上にいる場合のみ）', '# Shockwave damage (only if player on ground)'),
        (r'# 拡散弾', '# Spread shot'),
        (r'# 次の行動を選択', '# Choose next action'),
        (r'# 射撃', '# Shoot'),
        (r'# シールド', '# Shield'),
        (r'# 移動', '# Movement'),
        (r'# ジャンプ', '# Jump'),
        (r'シールド中は80%軽減', '80% reduction during shield'),
        (r'# ボスはノックバックしにくい', '# Boss is resistant to knockback'),
        (r'# ボス本体', '# Boss body'),
        (r'# ユーザー調整済み', '# User-adjusted'),
        (r'盾持ち: 正面からのダメージを50%軽減', 'Shield Bearer: 50% damage reduction from front'),
        (r'回復役: 周囲の敵を定期的に回復する', 'Healer: Periodically heals surrounding enemies'),
        (r'自爆型: 倒されると爆発し範囲ダメージ', 'Bomber: Explodes and deals area damage when defeated'),
        (r'狙撃型: 遠距離から予告線付きの高威力弾', 'Sniper: High-damage bullets with a warning line'),
        (r'正面（facing方向）からの攻撃はダメージ半減', 'Halve damage from front (facing direction)'),
        (r'# 盾を描画', '# Draw shield'),
        (r'爆発処理: プレイヤーと周囲の敵にダメージ', 'Explosion process: Damage player and nearby enemies'),
        (r'# 炎エフェクト', '# Flame effect'),
        (r'# 2 Wave ごとに 1体ずつ増え', '# increase by 1 every 2 waves'),
        (r'# 1秒ごとにダメージ', '# damage every second'),
        (r'# 短距離攻撃（剣）の持続タイマー', '# Melee attack (sword) duration timer'),
        (r'# 被弾時のノックバック/点滅タイマー', '# Hit knockback/flashing timer'),
        (r'# スマホモード向けジャンプ入力追跡用', '# Jump input tracking for smartphone mode'),
        (r'# 現在使用中のキャラクタークラスのインスタンス', '# Current character class instance'),
        (r'# 無敵タイマー', '# Invincibility timer'),
        (r'# キャラ選択時の設定保持用', '# Stores Reincarnator mode setting'),
        (r'# 落下中のみ', '# Only while falling'),
        (r'防御力で軽減 \(0ダメージも許容\)', 'Reduce by defense (0 damage allowed)'),
        (r'短い無敵で連続判定防止', 'Short invincibility prevents multiple hits'),
        (r'# 3秒で消滅', '# Expires in 3 seconds'),
        (r'# 地面に揃える', '# Align to ground'),
        (r'# READY中は動かない', '# No movement during READY'),
        (r'# 画面外への脱走を防止', '# Prevent screen escape'),
        (r'# 落下中のみ速度0にして接地させる', '# Grounding when falling'),
        (r'# 属性シナジー', '# Elemental synergy'),
        (r'# 凍結中はノックバックしない', '# No knockback while frozen'),
        (r'# 召喚エフェクト', '# Summoning effect'),
        (r'# 凍結中は青白く', '# Pale blue while frozen'),
        (r'# 炎エフェクト', '# Flame effect'),
        (r'# 模様', '# Patterns'),
        (r'# HPバー', '# HP Bar'),
        (r'# 衝撃波エフェクト', '# Shockwave effect'),
        (r'# UIの描画', '# Draw UI'),
        (r'# ロビーとセレクト画面のオーバーレイ', '# Lobby and select screen overlay'),
        (r'# メインボタン \(ENTER / タップで開始\)', '# Main button (ENTER / Tap to start)'),
        (r'# スマホモード切替ボタン', '# Smartphone mode toggle button'),
        (r'# カード背景', '# Card background'),
        (r'# テキスト', '# Text'),
        (r'# 改行対応は簡易的に', '# Simple newline handling'),
        (r'# スキル名の表示', '# Display skill names'),
        (r'# 転生者モードのトグル表示', '# Reincarnator mode toggle display'),
        (r'# スマホモードのトグル表示', '# Smartphone mode toggle display'),
        (r'# 現在のスキルを表示', '# Display current skills'),
        (r'# スキル名（クラス名から推測）', '# Skill name (inferred from class name)'),
        (r'# 新しいスキルを表示', '# Display new skill'),
        (r'# --- スマートフォン用バーチャルパッドの描画 \(最前面\) ---', '# --- Draw virtual pad for smartphone (topmost) ---'),
        (r'# 各ボタンの描画 \(半透明の白\)', '# Draw each button (semi-transparent white)'),
        (r'# 押されている間は明るく', '# Brighten while pressed'),
        (r'セーブデータの読み込み/作成', 'Load/Create Save Data'),
        (r'データの準備', 'Prepare Data'),
    ]


    for pattern, replacement in replacements:
        content = re.sub(pattern, replacement, content)

    # Specific multiline replacements or tricky ones
    content = content.replace('「Character Selectへ進む」', '"Proceed to Character Select"')
    content = content.replace('「スマホモード切り替え」', '"Toggle Smartphone Mode"')
    content = content.replace('「Character Selectへ進む」', '"Proceed to Character Select"')
    
    # Docstrings
    content = content.replace('プレイヤーの物理挙動、描画、キャラクター（クラス）の管理を行う。', 'Manages player physics, rendering, and character classes.')
    content = content.replace('プレイヤーが選択する各職業のベースクラス。', 'Base class for each character profession.')
    content = content.replace('Wave 5ごとに出現する巨大ボス。', 'Giant boss appearing every 5 waves.')
    content = content.replace('HPが高く、ジャンププレス、拡散弾、防御シールドを使用する。', 'High HP, uses jump press, spread shot, and shield.')

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

if __name__ == "__main__":
    translate_file("game/main.py")
    print("Translation attempt complete.")
